# file      : clean/buildfile
# copyright : Copyright (c) 2014-2019 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs  = libodb%lib{odb}
import libs += libodb-pgsql%lib{odb-pgsql}
import libs += libbutl%lib{butl}
import libs += libbbot%lib{bbot}

include ../libbrep/

exe{brep-clean}: {hxx ixx cxx}{* -clean-options} {hxx ixx cxx}{clean-options} \
                 ../libbrep/lib{brep} $libs

# Generated options parser.
#
if $cli.configured
{
  cli.cxx{clean-options}: cli{clean}

  cli.options += -I $src_root --include-with-brackets --include-prefix clean \
--guard-prefix CLEAN --generate-specifier --page-usage print_ --ansi-color   \
--long-usage

  # Include the generated cli files into the distribution and don't remove
  # them when cleaning in src (so that clean results in a state identical to
  # distributed).
  #
  cli.cxx{*}: dist  = true
  cli.cxx{*}: clean = ($src_root != $out_root)
}
