# file      : tests/web/xhtml/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs = libstudxml%lib{studxml}

exe{driver}: cxx{driver} $libs
exe{driver}: test.output = test.out
