# file      : tests/web/xhtml/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

include ../../../web/
exe{driver}: {hxx cxx}{*} ../../../web/libus{web}
exe{driver}: file{test.out}: test.stdout = true
