# file      : tests/ci/buildfile
# license   : MIT; see accompanying LICENSE file

dir = ../../brep/handler/ci/

include $dir

commons = data

./: testscript{* -{$commons}} common_testscript{$commons} {*/ -test/}{**} \
    $dir/exe{brep-ci-dir} $dir/exe{brep-ci-load}                          \
    doc{README} file{hello.tar.gz}

testscript{ci-dir}@./:  test = $out_base/$dir/brep-ci-dir
testscript{ci-load}@./: test = $out_base/$dir/brep-ci-load
