# file      : tests/ci/buildfile
# copyright : Copyright (c) 2014-2018 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

define common: file
common{*}: extension = testscript

dir = ../../brep/handler/ci/

include $dir

commons = data

./: testscript{* -{$commons}} common{$commons} \
    $dir/exe{brep-ci-dir} $dir/exe{brep-ci-load}

testscript{ci-dir}@./:  test = $out_base/$dir/brep-ci-dir
testscript{ci-load}@./: test = $out_base/$dir/brep-ci-load
