# file      : etc/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

./: file{** -buildfile}

*: install = data/etc/
*: install.subdirs = true # Recreate subdirectories.
