# file      : etc/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

./: file{brep-module.conf brep-apache2.conf} \
systemd/file{brep-load.service brep-load.timer}

install = data/etc/
install.subdirs = true # Recreate subdirectories.
