# file      : etc/buildfile
# copyright : Copyright (c) 2014-2015 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

define conf: file
conf{*}: extension = conf
conf{*}: install = data/etc

./: conf{brep-module brep-apache2}
