# file      : web/server/buildfile
# license   : MIT; see accompanying LICENSE file

# This is currently part of the brep apache module but lives in a separate
# directory. Thus the strange choices: libus{}, no header installation, etc.

# While we don't need to link to APR, we need to find its header location.
#
import libs  = libapr1%lib{apr-1}
import libs += libapreq2%lib{apreq2}
import libs += libbutl%lib{butl}

libus{web-server}: {hxx ixx txx cxx}{**} $libs

{hxx ixx txx}{*}: install = false
