# file      : migrate/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs  = libodb%lib{odb}
import libs += libodb-pgsql%lib{odb-pgsql}
import libs += libbutl%lib{butl}

include ../libbrep/

exe{brep-migrate}: {hxx ixx cxx}{* -migrate-options} \
                   {hxx ixx cxx}{   migrate-options} \
                   ../libbrep/lib{brep} $libs

# Generated options parser.
#
if $cli.configured
{
  cli.cxx{migrate-options}: cli{migrate}

  cli.options += -I $src_root --include-with-brackets                \
--include-prefix migrate --guard-prefix MIGRATE --generate-specifier \
--page-usage print_ --ansi-color --long-usage

  # Include generated cli files into the distribution.
  #
  cli.cxx{*}: dist = true
}
