# file      : migrate/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs  = libodb%lib{odb}
import libs += libodb-pgsql%lib{odb-pgsql}
import libs += libbutl%lib{butl}

include ../brep/

exe{brep-migrate}:                   \
{            cxx}{ migrate }         \
{hxx ixx     cxx}{ migrate-options } \
../brep/lib{brep} $libs

# Generated options parser.
#
{hxx ixx cxx}{migrate-options}: cli{migrate}

if $cli.configured
{
  cli.options += -I $src_root --include-with-brackets --include-prefix migrate \
--guard-prefix MIGRATE --generate-specifier --page-usage print_ --ansi-color \
--long-usage
}

# Include generated cli files into the distribution.
#
{hxx ixx cxx}{migrate-options}: dist = true
