# file      : doc/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

cmds =             \
brep-clean         \
brep-load          \
brep-migrate

define css: file
css{*}: extension = css

define xhtml: doc
xhtml{*}: extension = xhtml

./: {man1 xhtml}{$cmds}                         \
    css{common pre-box man} 	                \
    file{man-prologue.1 man-epilogue.1          \
         man-prologue.xhtml man-epilogue.xhtml}

./: doc{build2-repository-interface-manual.xhtml      \
        build2-repository-interface-manual-a4.pdf     \
	build2-repository-interface-manual-a4.ps      \
        build2-repository-interface-manual-letter.pdf \
	build2-repository-interface-manual-letter.ps} \
    css{code-box common doc pre-box toc} 	      \
    file{a4.html2ps letter.html2ps doc.html2ps}       \
    file{doc-prologue.xhtml doc-epilogue.xhtml        \
         manual.cli}

./: file{cli.sh}
