# file      : doc/buildfile
# license   : MIT; see accompanying LICENSE file

cmds =       \
brep-clean   \
brep-load    \
brep-migrate \
brep-monitor

./: {man1 xhtml}{$cmds}     \
    css{common pre-box man} \
    file{man-*}

./: doc{build2-repository-interface-manual*} \
    css{code-box common doc pre-box toc}     \
    file{manual.cli doc-* *.html2ps}

./: file{cli.sh}
