# file      : www/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

define css: file
css{*}: extension = css
css{*}: install = data/www/

define scss: file
scss{*}: extension = scss
scss{*}: install = data/www/

./: css{common brep-common					\
        package-details package-details-body 			\
        package-search package-search-body 			\
        package-version-details package-version-details-body 	\
        repository-details repository-details-body}       	\
    scss{package-details package-search package-version-details \
         repository-details}
