# file      : www/buildfile
# copyright : Copyright (c) 2014-2018 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

define css: file
css{*}: extension = css
css{*}: install = data/www/

define scss: file
scss{*}: extension = scss
scss{*}: install = data/www/

./: css{*} scss{*}
