// -*- C++ -*-
//
// This file was generated by CLI, a command line interface
// compiler for C++.
//

#ifndef MONITOR_MODULE_OPTIONS_HXX
#define MONITOR_MODULE_OPTIONS_HXX

// Begin prologue.
//
//
// End prologue.

#include <mod/module-options.hxx>

namespace brep
{
  namespace options
  {
    class module: public ::brep::options::build_task
    {
      public:
      module ();

      // Return true if anything has been parsed.
      //
      bool
      parse (int& argc,
             char** argv,
             bool erase = false,
             ::brep::cli::unknown_mode option = ::brep::cli::unknown_mode::fail,
             ::brep::cli::unknown_mode argument = ::brep::cli::unknown_mode::stop);

      bool
      parse (int start,
             int& argc,
             char** argv,
             bool erase = false,
             ::brep::cli::unknown_mode option = ::brep::cli::unknown_mode::fail,
             ::brep::cli::unknown_mode argument = ::brep::cli::unknown_mode::stop);

      bool
      parse (int& argc,
             char** argv,
             int& end,
             bool erase = false,
             ::brep::cli::unknown_mode option = ::brep::cli::unknown_mode::fail,
             ::brep::cli::unknown_mode argument = ::brep::cli::unknown_mode::stop);

      bool
      parse (int start,
             int& argc,
             char** argv,
             int& end,
             bool erase = false,
             ::brep::cli::unknown_mode option = ::brep::cli::unknown_mode::fail,
             ::brep::cli::unknown_mode argument = ::brep::cli::unknown_mode::stop);

      bool
      parse (::brep::cli::scanner&,
             ::brep::cli::unknown_mode option = ::brep::cli::unknown_mode::fail,
             ::brep::cli::unknown_mode argument = ::brep::cli::unknown_mode::stop);

      // Option accessors.
      //
      // Implementation details.
      //
      protected:
      bool
      _parse (const char*, ::brep::cli::scanner&);

      private:
      bool
      _parse (::brep::cli::scanner&,
              ::brep::cli::unknown_mode option,
              ::brep::cli::unknown_mode argument);

      public:
    };
  }
}

#include <monitor/module-options.ixx>

// Begin epilogue.
//
//
// End epilogue.

#endif // MONITOR_MODULE_OPTIONS_HXX
