# file      : brep/handler/upload/buildfile
# license   : MIT; see accompanying LICENSE file

./: exe{brep-upload-bindist} exe{brep-upload-bindist-clean}

include ../

exe{brep-upload-bindist}: in{upload-bindist} bash{upload} ../bash{handler}

[rule_hint=bash] \
exe{brep-upload-bindist-clean}: in{upload-bindist-clean}

bash{upload}: in{upload} ../bash{handler}
