# file      : brep/handler/upload/buildfile
# license   : MIT; see accompanying LICENSE file

./: exe{brep-upload-bindist brep-upload-bindist-clean brep-upload-bindist-sync}

include ../

exe{brep-upload-bindist}: in{upload-bindist} bash{upload} ../bash{handler}

bash{upload}: in{upload} ../bash{handler}

exe{brep-upload-bindist-clean}: in{upload-bindist-clean} ../bash{utility}
exe{brep-upload-bindist-sync}:  in{upload-bindist-sync}  ../bash{utility}
