# file      : brep/submit/buildfile
# copyright : Copyright (c) 2014-2018 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import mods  = libbutl.bash%bash{manifest-parser}
import mods += libbutl.bash%bash{manifest-serializer}

exe{brep-submit-dir}: in{submit-dir} bash{submit} $mods
bash{submit}: in{submit} $mods # @@ Currently doesn't depend on manifest-parser.

#install.bin.subdirs = true
#install.subdirs = true
