# file      : brep/submit/buildfile
# copyright : Copyright (c) 2014-2018 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import mods  = libbutl.bash%bash{manifest-parser}
import mods += libbutl.bash%bash{manifest-serializer}

./: exe{brep-submit-dir} exe{brep-submit-git}

exe{brep-submit-dir}: in{submit-dir} bash{submit}
exe{brep-submit-git}: in{submit-git} bash{submit-git} bash{submit}

bash{submit}:     in{submit} $mods
bash{submit-git}: in{submit-git} bash{submit}
