# file      : loader/buildfile
# copyright : Copyright (c) 2014-2015 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

using cli

import libs += libbpkg%lib{bpkg}
import libs += libbutl%lib{butl}
import libs += libodb-pgsql%lib{odb-pgsql}
import libs += libodb%lib{odb}

include ../brep/

loader = cxx{loader} cli.cxx{options}
exe{brep-loader}: $loader ../brep/libso{brep} $libs

cli.options += -I $src_root --include-with-brackets --include-prefix loader \
--guard-prefix LOADER

cli.cxx{options}: cli{options}
