# file      : brep/handler/buildfile
# license   : MIT; see accompanying LICENSE file

import mods  = libbutl.bash%bash{manifest-parser}
import mods += libbutl.bash%bash{manifest-serializer}

./: bash{handler} submit/ ci/

bash{handler}: in{handler} $mods
