# file      : brep/handler/buildfile
# license   : MIT; see accompanying LICENSE file

import mods  = libbutl.bash%bash{manifest-parser}
import mods += libbutl.bash%bash{manifest-serializer}
import mods += bpkg-util%bash{package-archive}

./: bash{utility handler} submit/ ci/ upload/

bash{utility}: in{utility}
bash{handler}: in{handler} bash{utility} $mods
