# file      : tests/submit/buildfile
# license   : MIT; see accompanying LICENSE file

dir = ../../brep/handler/submit/

include $dir

commons = data

./: testscript{* -{$commons}} common_testscript{$commons} {*/ -test/}{**} \
    $dir/exe{brep-submit-dir}                                             \
    $dir/exe{brep-submit-git}                                             \
    $dir/exe{brep-submit-pub}                                             \
    file{hello.tar.gz} doc{README}

testscript{submit-dir}@./: test = $out_base/$dir/brep-submit-dir
testscript{submit-git}@./: test = $out_base/$dir/brep-submit-git
testscript{submit-pub}@./: test = $out_base/$dir/brep-submit-pub
