# file      : tests/submit/buildfile
# copyright : Copyright (c) 2014-2018 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

define common: file
common{*}: extension = testscript

dir = ../../brep/handler/submit/

include $dir

commons = data

./: testscript{* -{$commons}} common{$commons} {*/ -test/}{**} \
    $dir/exe{brep-submit-dir} $dir/exe{brep-submit-git}

testscript{submit-dir}@./: test = $out_base/$dir/brep-submit-dir
testscript{submit-git}@./: test = $out_base/$dir/brep-submit-git
