# file      : tests/load/buildfile
# license   : MIT; see accompanying LICENSE file

import libs += libbpkg%lib{bpkg}
import libs += libbutl%lib{butl}
import libs += libodb-pgsql%lib{odb-pgsql}
import libs += libodb%lib{odb}

include ../../libbrep/

./: exe{driver} file{loadtab cert *.pem openssl.cnf */**}

exe{driver}: {hxx cxx}{*} ../../libbrep/lib{brep} $libs

# Disable until testscript is implemented.
#
exe{driver}: test = false

# precondition: the environment is setup according to INSTALL-DEV file.
# test:
# ./driver ../../load/brep-load --bpkg ../../../bpkg/bpkg/bpkg ./loadtab
