# file      : tests/load/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs += libbpkg%lib{bpkg}
import libs += libbutl%lib{butl}
import libs += libodb-pgsql%lib{odb-pgsql}
import libs += libodb%lib{odb}

include ../../brep/

exe{driver}: cxx{driver} ../../brep/lib{brep} $libs

# Disable for now until build2 test module supports running custom
# commands, pre/post steps.
#
exe{driver}: test = false

# precondition: PostgreSQL server running port 8432 with brep schema created.
# test:
# ./driver ../../load/brep-load --db-host localhost --db-port 8432 ./r.conf
