# file      : brep/buildfile
# copyright : Copyright (c) 2014-2015 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

using cli

.: libso{brep brep-apache}

# brep library build rules.
#
import libs += libodb%lib{odb}
import libs += libodb-pgsql%lib{odb-pgsql}
import libs += libbpkg%lib{bpkg}

brep = cxx{package package-odb}

libso{brep}: $brep $libs
libso{brep}: cxx.export.poptions = -I$out_root -I$src_root

# brep-apache library build rules.
#
import libs += libstudxml%lib{studxml}

brep = cxx{diagnostics module services package-search package-version-search \
       shared-database page} cli.cxx{options}
web = ../web/apache/cxx{request service} ../web/cxx{mime-url-encoding}

libso{brep-apache}: $brep $web libso{brep} $libs

# Set option prefix to the empty value to handle all unknown request parameters
# uniformly with a single catch block.
#
# @@ Adding --option-prefix "" leads to appearing the following warnings
#    related to options _parse methed:
# brep/options.cxx:663:33: warning: unused parameter ‘opt_mode’ [-Wunused-parameter]
#             ::cli::unknown_mode opt_mode,
#
cli.options += -I $src_root --include-with-brackets --include-prefix brep \
--guard-prefix BREP --generate-file-scanner --suppress-usage --option-prefix ""

cli.cxx{options}: cli{options}
