# file      : brep/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

define sql: file
sql{*}: extension = sql
sql{*}: install = data/

# lib{brep}
#
import libs += libodb%lib{odb}
import libs += libodb-pgsql%lib{odb-pgsql}
import libs += libbpkg%lib{bpkg}

lib{brep}:                          \
{hxx         cxx}{ package        } \
{file           }{ package.xml    } \
{hxx ixx     cxx}{ package-odb    } \
{hxx            }{ package-extra  } \
{hxx         cxx}{ package-traits } \
{hxx         cxx}{ database-lock  } \
{hxx            }{ types          } \
{hxx            }{ utility        } \
{hxx            }{ version        } \
{hxx            }{ wrapper-traits } \
$libs                               \
sql{package package-extra}

lib{brep}: cxx.export.poptions = -I$out_root -I$src_root

# Install into the brep/ subdirectory of, say, /usr/include/.
#
install.include = $install.include/brep/
