# file      : load/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs += libbpkg%lib{bpkg}
import libs += libbutl%lib{butl}
import libs += libodb-pgsql%lib{odb-pgsql}
import libs += libodb%lib{odb}

include ../brep/

exe{brep-load}:                   \
{            cxx}{ load         } \
{hxx ixx     cxx}{ load-options } \
../brep/lib{brep} $libs

cli.options += -I $src_root --include-with-brackets --include-prefix load \
--guard-prefix LOAD

{hxx ixx cxx}{load-options}: cli{load}
