# file      : load/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs  = libodb%lib{odb}
import libs += libodb-pgsql%lib{odb-pgsql}
import libs += libbutl%lib{butl}
import libs += libbpkg%lib{bpkg}

include ../brep/

exe{brep-load}:                    \
{            cxx}{ load          } \
{hxx ixx     cxx}{ load-options  } \
{hxx         cxx}{ types-parsers } \
../brep/lib{brep} $libs

cli.options += -I $src_root --include-with-brackets --include-prefix load \
--guard-prefix LOAD --generate-specifier --page-usage print_ --ansi-color \
--cxx-prologue "#include <load/types-parsers>" \
--long-usage

{hxx ixx cxx}{load-options}: cli{load}
