# file      : libbrep/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

define sql: file
sql{*}: extension = sql
sql{*}: install = data/

import int_libs  = libodb%lib{odb}
import int_libs += libodb-pgsql%lib{odb-pgsql}
import int_libs += libbutl%lib{butl}
import int_libs += libbpkg%lib{bpkg}
import int_libs += libbbot%lib{bbot}

lib{brep}:                             \
{hxx         cxx}{ build             } \
{file           }{ build.xml         } \
{hxx ixx     cxx}{ build-odb         } \
{hxx            }{ build-extra       } \
{hxx            }{ build-package     } \
{hxx ixx     cxx}{ build-package-odb } \
{hxx         cxx}{ common            } \
{hxx ixx     cxx}{ common-odb        } \
{hxx         cxx}{ package           } \
{file           }{ package.xml       } \
{hxx ixx     cxx}{ package-odb       } \
{hxx            }{ package-extra     } \
{hxx         cxx}{ package-traits    } \
{hxx         cxx}{ database-lock     } \
{hxx            }{ types             } \
{hxx            }{ utility           } \
{hxx            }{ version           } \
{hxx            }{ wrapper-traits    } \
                   $int_libs           \
sql{build build-extra package package-extra}

hxx{version}: in{version} $src_root/file{manifest}
hxx{version}: dist = true

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version.
#
if $version.pre_release
  lib{brep}: bin.lib.version = @"-$version.project_id"
else
  lib{brep}: bin.lib.version = @"-$version.major.$version.minor"

lib{brep}: cxx.export.poptions = "-I$out_root" "-I$src_root"
lib{brep}: cxx.export.libs = $int_libs

# Install into the libbrep/ subdirectory of, say, /usr/include/.
#
install.include = $install.include/libbrep/
