# file      : libbrep/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

define sql: file
sql{*}: extension = sql
sql{*}: install = data/

# @@ ODB: these are ODB changelogs that are both generated and stored in the
#         repository (what if src != out?). Will need to think how to handle
#         them properly (always generate in src_base?).
#
define xml: file
xml{*}: extension = xml

import int_libs  = libodb%lib{odb}
import int_libs += libodb-pgsql%lib{odb-pgsql}
import int_libs += libbutl%lib{butl}
import int_libs += libbpkg%lib{bpkg}
import int_libs += libbbot%lib{bbot}

lib{brep}:                                                              \
  {hxx ixx txx cxx}{* -version -*-odb}                                  \
  {hxx            }{version}                                            \
  {hxx ixx     cxx}{common-odb package-odb build-odb build-package-odb} \
  $int_libs xml{*} sql{*}

hxx{version}: in{version} $src_root/file{manifest}
hxx{version}: dist = true

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version.
#
if $version.pre_release
  lib{brep}: bin.lib.version = @"-$version.project_id"
else
  lib{brep}: bin.lib.version = @"-$version.major.$version.minor"

lib{brep}: cxx.export.poptions = "-I$out_root" "-I$src_root"
lib{brep}: cxx.export.libs = $int_libs

# Install into the libbrep/ subdirectory of, say, /usr/include/.
#
install.include = $install.include/libbrep/
