# file      : brep/handler/ci/buildfile
# copyright : Copyright (c) 2014-2019 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

./: exe{brep-ci-dir} exe{brep-ci-load}

include ../

exe{brep-ci-dir}:  in{ci-dir}  bash{ci} ../bash{handler}
exe{brep-ci-load}: in{ci-load} bash{ci} ../bash{handler}

bash{ci}: in{ci} ../bash{handler}
