# file      : brep/handler/ci/buildfile
# copyright : Copyright (c) 2014-2018 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

./: exe{brep-ci-dir}

include ../

exe{brep-ci-dir}: in{ci-dir} bash{ci} ../bash{handler}

bash{ci}: in{ci} ../bash{handler}
