# file      : mod/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

define mod: libso
mod{*}: bin.libprefix = mod_
mod{*}: install = libexec

import libs += libodb%lib{odb}
import libs += libodb-pgsql%lib{odb-pgsql}
import libs += libbpkg%lib{bpkg}
import libs += libstudxml%lib{studxml}

include ../brep/

mod{brep}:                                                     \
              {hxx         cxx}{ database                    } \
              {hxx         cxx}{ database-module             } \
              {hxx         cxx}{ diagnostics                 } \
              {hxx         cxx}{ mod-package-details         } \
              {hxx         cxx}{ mod-package-search          } \
              {hxx         cxx}{ mod-package-version-details } \
              {hxx         cxx}{ mod-repository-details      } \
              {hxx         cxx}{ mod-repository-root         } \
              {hxx         cxx}{ module                      } \
	      {hxx ixx     cxx}{ options                     } \
              {hxx            }{ options-types               } \
              {hxx         cxx}{ page                        } \
              {            cxx}{ services                    } \
              {hxx         cxx}{ types-parsers               } \
       ../web/{hxx         cxx}{ mime-url-encoding           } \
       ../web/{hxx            }{ module                      } \
       ../web/{hxx            }{ xhtml                       } \
       ../web/{hxx         cxx}{ xhtml-fragment              } \
../web/apache/{hxx            }{ log                         } \
../web/apache/{hxx ixx     cxx}{ request                     } \
../web/apache/{hxx     txx cxx}{ service                     } \
../web/apache/{hxx            }{ stream                      } \
../brep/lib{brep} $libs

# Don't install any of the module's headers.
#
{hxx ixx txx}{*}: install = false

#../web/{hxx ixx txx}{*}: install = false # @@ BC
../web/:
{
  {hxx ixx txx}{*}: install = false
}

# Set option prefix to the empty value to handle all unknown request parameters
# uniformly with a single catch block.
#
cli.options += --std c++11 -I $src_root --include-with-brackets \
--include-prefix mod --guard-prefix MOD \
--cxx-prologue "#include <mod/types-parsers>" \
--cli-namespace brep::cli --generate-file-scanner --suppress-usage \
--generate-modifier --generate-description --option-prefix ""

{hxx ixx cxx}{options}: cli{options}
